### ISSUE TITLE
Can we rename "merge" to "reconcile" ?

### ISSUE THREAD

**Issue by necula01** [necula01/bond#11]
It seems that the terminology "merge" is not really appropriate. I think that 

BOND_RECONCILE=accept is a better terminology. 

What do you think?

**Comment by xkrogen** [comment]
Agreed. It's also more consistent with bond_reconcile.

**Comment by necula01** [comment]
I have made that change for py. Please close when you change for rb. Note that bond_reconcile.py now is invoked with argument --reconcile.

**Comment by xkrogen** [comment]
Fixed
