### ISSUE TITLE
Allow bond.spy in production code

### ISSUE THREAD

**Issue by necula01** [necula01/bond#12]
While looking at some of the uses of Bond I realized that sometimes you want to spy some intermediate values in production code. With the new design we have the option to break the function there (ugly), or to create an empty function with a spy_point annotation. 

I'd say we allow bond.spy in production code. All we need to do is to make sure it does return immediately if not in test.

**Comment by necula01** [comment]
Leaving open for rbond to catch up.

**Comment by xkrogen** [comment]
Fixed in rbond.
