### ISSUE TITLE
API differences python vs ruby

### ISSUE THREAD

**Issue by necula01** [necula01/bond#15]
I noticed the following:

bond.testing vs bond.TESTING
:agent_result_none vs bond.AGENT_RESULT_NONE
:agent_result_continue vs ...

It is not most important to keep the APIs identical, but we have to think how will be take advantage of join documentation or tutorials.

**Comment by xkrogen** [comment]
Yeah, I was thinking about this too. I think some things are inevitably
going to be different, e.g. for a special return value in Ruby you really
should be using a symbol but Python doesn't have this concept. I was
thinking it should be pretty simple to extend your code example switching
code to replace small inline snippets as well such that you could just pick
your language and the entire tutorial would change where appropriate?

**Comment by necula01** [comment]
A related issue, should we change bond.TESTING into bond.is_active() ? The idea with TESTING being so visible was to have a very clear marker for testing code. But TESTING is not a constant, so we should not use capital letters.

**Comment by xkrogen** [comment]
Yeah, that's why I didn't call it Bond.TESTING in Ruby, I just couldn't
bring myself to treat an all-caps variable as mutable. This is another
situation where Ruby convention goes against what Python would have - in
Ruby that would be 'Bond#active?', though in this case it might be worth it
to deviate from
convention slightly to keep the APIs in sync (maybe we could provide
both?). In any case I'm in favor of turning it into a method.

**Comment by necula01** [comment]
For this inline replacement to work I need to figure out a way to make
sphinx add <span> elements with specific classes. It can do this for <div>
if I use ..container:: but not sure it can be done for inline.

George.

**Comment by necula01** [comment]
Ok, we'll call it bond.active in Python and Bond#active? in Ruby. I still
hesitate though over the lost of the visual separation, but each project
can create their own synonym, if it is a method.

George.

**Comment by necula01** [comment]
I am going to transition pybond to bond.active but leave TESTING as a deprecated synonym

**Comment by xkrogen** [comment]
Changed to Bond#active? in Ruby. Leaving open until we deal with the API discrepancies in the tutorial / documentation.

**Comment by xkrogen** [comment]
Going to say that this is resolved through our tab system.
