### ISSUE TITLE
bring back `ignore` in some form

### ISSUE THREAD

**Issue by xkrogen** [necula01/bond#18]
Writing the heat_watcher test has made me realize that the `ignore` option is really nice for situations where you want to mock but not spy (in the heat_watcher example, I really don't want to be observing all of the calls to `get_current_time`) but this isn't possible at the moment.

**Comment by necula01** [comment]
I very much agree.

**Comment by xkrogen** [comment]
This was added in commits f316761 (Python) and fe9dc80 (Java, Ruby) via the `mock_only` option on spy points.
