### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by xkrogen** [necula01/bond#20]
Is there a license you usually use for open source / one we're supposed to use because of Berkeley? Started thinking about this because RubyGems is mildly unhappy if you don't specify a license.

**Comment by necula01** [comment]
We do need a license. I would prefer BSD license.

George.

**Comment by xkrogen** [comment]
Do you have between 3-clause and 2-clause?

**Comment by xkrogen** [comment]
Also for the <owner> portion of the license, would that be us? UC Berkeley?
Not very familiar with this sort of thing...

**Comment by necula01** [comment]
Neither am I. I did not know there is an owner. I know that UCB want to be
explicitly released of any liability.

George.
