### ISSUE TITLE
0.1.0 not published on mvn repo

### ISSUE THREAD

**Issue by milieu** [necula01/bond#25]
The [getting started documentation](http://necula01.github.io/bond/gettingstarted.html#tab-Java-1) lists a Maven dependency for Bond that can't be found. [Searching for Bond](http://mvnrepository.com/search?q=bond) also shows nothing.

**Comment by xkrogen** [comment]
Hi! We're aware and I was just actively working on fixing this. It should be available in the next few days.

**Comment by necula01** [comment]
This reminds me that even the pybond is not properly published.

George.

**Comment by xkrogen** [comment]
Yeah, looking into that was next on my todo list after getting the Java
version properly deployed.

Erik

**Comment by xkrogen** [comment]
It's available now: https://search.maven.org/#artifactdetails%7Corg.necula.bond%7Cbond%7C0.1.0%7Cpom
