### ISSUE TITLE
[pybond] bug with reconciliation

### ISSUE THREAD

**Issue by xkrogen** [necula01/bond#7]
Right now it seems that the reconciliation too aggressively ignores whitespace. It seems to consider these as matching:

`"__spy_point_name": "AnnotationTests.annotated_class_method",`
`"__spy_point_name": "AnnotationTes    ts.annotated_class_method",`

which is clearly not correct

**Comment by necula01** [comment]
I have replaced "diff -w" (ignore all whitespace) with "diff -b" (ignore whitespace changes).
