### ISSUE TITLE
ease of passing tests if you change the observation directory

### ISSUE THREAD

**Issue by xkrogen** [necula01/bond#8]
Right now if you change the observation directory, on the next run, all of your tests will pass without warning or anything. It would be really easy to accidentally change the observation directory, break a bunch of things, run the tests and have them succeed, and then check in that code. It's kind of an obscure situation but I kind of just almost did it to myself (because I was fiddling around with the code that sets the observation directory, broke it, and all of my tests were passing). 

Not sure if we need to do anything about this (beyond maybe a comment in the documentation), but I think it's something to consider.

**Comment by necula01** [comment]
Maybe it makes sense to consider that the first time you reconcile changes the reference file is empty. This forces you to look at the first saved observation, as you should. And it will also have the additional effect of signaling when you changed the observation directory.

**Comment by xkrogen** [comment]
Yeah, I agree with this. You should need to manually verify the results the
first time, it doesn't really make sense that it automatically assumes the
first run is correct.

**Comment by necula01** [comment]
I have fixed this for pybond.

**Comment by xkrogen** [comment]
Fixed in rbond as well.
