### ISSUE TITLE
[rbond] observing blocks?

### ISSUE THREAD

**Issue by xkrogen** [necula01/bond#9]
In Ruby, it's pretty common to pass a block as an argument to a method. Should we include this in our observation? If so, how? The blocks can be pretty important to the program's execution but I see no easy way to include them in observations.

**Comment by necula01** [comment]
Are you thinking of spying the blocks as data, or with spy_points (as
methods to be spied)? The former does not make sense, for the latter you
can do if you name it.

This passing-blocks style is called higher-order programming and it is just
a different way to organize the flow of control. Bond is for spying the
first-order data values, not the higher-order ones. Even in Python you
would not spy the lambdas.

George.

**Comment by xkrogen** [comment]
I was thinking the former, but yeah, I suppose you're right that it doesn't really make sense. Nevermind.
